name = "google-proxy"
version = "0.1.0"
component = "/Users/colinrozzi/work/actor-registry/google-proxy/./target/wasm32-unknown-unknown/release/google_proxy.wasm"
init_state = "/Users/colinrozzi/work/actor-registry/google-proxy/init.json"

[permission_policy.message_server]
type = "inherit"

[permission_policy.file_system]
type = "inherit"

[permission_policy.http_client]
type = "inherit"

[permission_policy.http_framework]
type = "inherit"

[permission_policy.runtime]
type = "inherit"

[permission_policy.supervisor]
type = "inherit"

[permission_policy.store]
type = "inherit"

[permission_policy.timing]
type = "inherit"

[permission_policy.process]
type = "inherit"

[permission_policy.environment]
type = "inherit"

[permission_policy.random]
type = "inherit"

[[handlers]]
type = "message-server"

[handlers.config]

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "store"

[handlers.config]

[[handlers]]
type = "http-client"

[handlers.config]

[[handlers]]
type = "environment"

[handlers.config]
allowed_vars = ["GEMINI_API_KEY"]
allow_list_all = false
