name = "google-proxy"
version = "0.1.0"
component = "/Users/colinrozzi/work/actor-registry/google-proxy/./target/wasm32-unknown-unknown/release/google_proxy.wasm"
init_state = "/Users/colinrozzi/work/actor-registry/google-proxy/init.json"

[[handler]]
type = "message-server"

[[handler]]
type = "runtime"

[[handler]]
type = "store"

[[handler]]
type = "http-client"

[[handler]]
type = "environment"
allowed_vars = ["GEMINI_API_KEY"]
allow_list_all = false
