name = "google-proxy"
version = "0.1.0"
component_path = "/Users/colinrozzi/work/actor-registry/google-proxy/./target/wasm32-unknown-unknown/release/google_proxy.wasm"
init_state = "/Users/colinrozzi/work/actor-registry/google-proxy/init.json"

[[handlers]]
type = "message-server"

[handlers.config]

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "store"

[handlers.config]

[[handlers]]
type = "http-client"

[handlers.config]
